### ISSUE TITLE
Linear Regression|python

### ISSUE THREAD

**Issue by PrasanthChettri** [div-bargali/Data-Structures-and-Algorithms#330]
## **`Linear Regression`** -

**what will change** -
Add Linear Regression algorithm which is a machine learning algorithm
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by PrasanthChettri** [comment]
Can I be assigned this issue ?

**Comment by liamm91** [comment]
Is it too late to contribute?

**Comment by PrasanthChettri** [comment]
@liamm91  Yeah man you can take this issue, I am currently not in a position to contribute cause of 'rona

**Comment by liamm91** [comment]
thanks, hope you get better!

**Comment by iepsenn** [comment]
Hi, I want to be assigned on this issue

**Comment by hemanth-kotagiri** [comment]
Hello, @liamm91. It has been over a couple of weeks since this issue being assigned to you. And, I can see that you have not pushed any new commits to your fork as well. 
I request you to raise a PR as soon as possible and please respond here if you are working on the implementations.

**Any further delay or not responding to this comment would result in assigning this issue to the next individual.**

Thanks!

**Comment by hemanth-kotagiri** [comment]
@iepsenn, are you willing to work on this? If so, I'd assign you soon for this issue if @liamm91 doesn't respond.

Thanks!
